version: '3.8'

services:
  db_mysql:
    image: mysql:8.0.46
    container_name: mysql_vendas_prod
    environment:
      MYSQL_ROOT_PASSWORD: RootPassword123!
    ports:
      - "3306:3306"
    volumes:
      - ./SCRIPTS:/docker-entrypoint-initdb.d
